services:
  - type: web
    name: employee-management-system
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn projectname.wsgi:application"
    envVars:
      - key: DJANGO_SECRET_KEY
        value: your_secret_key
      - key: DJANGO_DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: your_render_domain
